app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => ['web']], function () {
    Route::auth();

    Route::group(['middleware' => ['auth']], function () {
        Route::get('/stories/create', 'HomeController@index');
        Route::post('/stories/create', 'HomeController@store');

        Route::get('/stories/unpublished', 'StoryController@unpublishedStories');
        Route::get('/stories/{id}/edit', 'StoryController@show');
        Route::put('/stories/{id}/edit', 'StoryController@edit');
        Route::delete('/stories/{id}', 'StoryController@delete');
    });

    Route::get('/stories', 'StoryController@index');
    Route::post('/fetchLink', 'StoryController@fetchExternalLink');
    Route::get('/', 'StoryController@listStories');
    Route::get('/login', 'HomeController@showLoginPage');
    Route::get('/stories/{slug}', 'StoryController@storyView');
});


Route::group(['middleware' => 'api'], function () {
    Route::get('/categories', 'CategoryController@index');
    Route::get('/thumbnails/{thumbnail}', 'ThumbnailController@show');
});

app/Story.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Config;

class Story extends Model
{
    use SoftDeletes;

    protected $guarded = [
        'id',
        'created_at',
        'updated_at',
        'deleted_at'
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at'
    ];

    protected $hidden = [
        'deleted_at'
    ];

    protected $table = 'stories';

    public function getThumbnailUrlAttribute($value) {
        $url = 'https://s3.amazonaws.com/' . Config::get('filesystems.disks.s3.bucket') . '/images/' . $value;
        return url($url);
    }

    public function categories() {
        return $this->belongsToMany(Category::class)->withTimestamps();
    }
}

resources/views/editForm.blade.php
@extends('layouts.app')
<title>Edit Story</title>

<!-- Main Content -->
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading ">
                        <div class="row">
                            <div class="col-md-6 ">
                                <strong>Edit Story</strong>
                            </div>
                            <div class="col-md-6">
                                <form class="pull-right" method="post" action="{{url("/stories/$story->id")}}">
                                    {{csrf_field()}}
                                    <input type="hidden" name="_method" value="DELETE">
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form class="form-horizontal" enctype="multipart/form-data" role="form" method="POST"
                              action="{{ url("/stories/$story->id/edit") }}">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="PUT">

                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                <label for="title" class="col-md-4 control-label">Title</label>

                                <div class="col-md-6">
                                    <input id="title" type="text" class="form-control" name="title"
                                           value="{{ old('title') == null ?$story->title :old('title') }}">

                                    @if ($errors->has('title'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                                <label for="description" class="col-md-4 control-label">Description</label>

                                <div class="col-md-6">
                                    <textarea id="description" class="form-control" name="description"
                                              style="max-width: 100%">{{ old('description') == null ?$story->description :old('description') }}</textarea>

                                    @if ($errors->has('description'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('article_link') ? ' has-error' : '' }}">
                                <label for="article_link" class="col-md-4 control-label">Article Link</label>

                                <div class="col-md-6">
                                    <input id="article_link" type="text" class="form-control" name="article_link"
                                           value="{{ old('article_link') == null ?$story->article_link :old('article_link') }}">

                                    @if ($errors->has('article_link'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('article_link') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('thumbnail') ? ' has-error' : '' }}">
                                <label for="thumbnail" class="col-md-4 control-label">Thumbnail</label>

                                <div class="col-md-6">
                                    <img id="image" style="max-width: 50%; max-height: 50%" class="img-thumbnail"
                                         src="{{$story->thumbnail_url}}">
                                    <input id="thumbnail" type="file" class="form-control" name="thumbnail">

                                    @if ($errors->has('thumbnail'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('thumbnail') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('categories') ? ' has-error' : '' }}">
                                <label for="duration" class="col-md-4 control-label">Category</label>
                                <div class="col-md-6" id="multi_select">
                                    <select id="select" name="categories[]" class="js-example-basic-multiple js-states form-control" multiple="multiple">
                                        @foreach($categories as $category)
                                            <option value="{{ $category->id }}">{{ $category->title }}</option>
                                        @endforeach
                                        @if(isset($selectedCategories))
                                            @foreach($selectedCategories as $category)
                                                <option selected="selected" value="{{ $category->id }}">{{ $category->title }}</option>
                                            @endforeach
                                        @endif
                                    </select>
                                    @if ($errors->has('categories'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('categories') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="published"
                                                   value=1 {{old('published') != null ?'checked' :($story->published_at == null ?'' :'checked') }}>Publish
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Edit This Story
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.js-example-basic-multiple').select2({
                placeholder: "Select a category",
                allowClear: true
            });
        });

        // $('.select2-selection__rendered').append("<li class='select2-selection__choice' title='cupiditate'><span class='select2-selection__choice__remove' role='presentation'>×</span>cupiditate</li>");

        document.getElementById("thumbnail").onchange = function () {
            var reader = new FileReader();

            reader.onload = function (e) {
                // get loaded data and render thumbnail.
                document.getElementById("image").src = e.target.result;
            };

            // read the image file as a data URL.
            reader.readAsDataURL(this.files[0]);
        };

    </script>
@endsection

resources/views/form.blade.php
@extends('layouts.app')
        <title>Create Story</title>

        <!-- Main Content -->
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Create a new Story</div>
                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form class="form-horizontal" enctype="multipart/form-data" role="form" method="POST" action="{{ url('/stories/create') }}">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                <label for="title" class="col-md-4 control-label">Title</label>

                                <div class="col-md-6">
                                    <input id="title" type="text" class="form-control" name="title" value="{{ old('title') }}">

                                    @if ($errors->has('title'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                                <label for="description" class="col-md-4 control-label">Description</label>

                                <div class="col-md-6">
                                    <textarea id="description" class="form-control" name="description"
                                              style="max-width: 100%">{{ isset($attrs) ?$attrs["description"] :old('description') }}</textarea>

                                    @if ($errors->has('description'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('article_link') ? ' has-error' : '' }}">
                                <label for="article_link" class="col-md-4 control-label">Article Link</label>

                                <div class="col-md-6">
                                    <input id="article_link" type="text" class="form-control" name="article_link"
                                           value="{{ isset($attrs) ?$attrs["article_link"] :old('article_link') }}">

                                    @if ($errors->has('article_link'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('article_link') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('thumbnail') ? ' has-error' : '' }}">
                                <label for="thumbnail" class="col-md-4 control-label">Thumbnail</label>

                                <div class="col-md-6">
                                    <input id="thumbnail" type="file" class="form-control" name="thumbnail">

                                    @if ($errors->has('thumbnail'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('thumbnail') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('categories') ? ' has-error' : '' }}">
                                <label for="duration" class="col-md-4 control-label">Category</label>
                                <div class="col-md-6" id="multi_select">
                                    <select id="select" name="categories[]" class="js-example-basic-multiple js-states form-control" multiple="multiple">
                                        @foreach($categories as $category)
                                            <option value="{{ $category->id }}">{{ $category->title }}</option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('categories'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('categories') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="published" value=1 {{old('published') != null ?'checked' :'' }}>Publish
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Create This Story
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.js-example-basic-multiple').select2({
                placeholder: "Select a category",
                allowClear: true
            });
        });
    </script>
@endsection

resources/views/storyList.blade.php
@extends('layouts.app')
<title>Stories List</title>

@section('header')
    <link rel="stylesheet" href={{ url('/css/stories.css') }}>
@endsection

@section('meta')
    {{--Twitter--}}
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Startup Briefs">
    <meta name="twitter:description"
          content="Startup Briefs is a platform which reduces the length of news while retaining the content, hence saving time of reader">
    <meta name="twitter:image" content="https://s3.amazonaws.com/vaetas/images/startup_briefs_logo.png">

    {{--Facebook--}}
    <meta property="fb:app_id" content="1648507378769295">
    <meta property="og:url" content="{{ url('/') }}">
    <meta property="og:type" content="Startup Briefs">
    <meta property="og:title" content="Startup Briefs">
    <meta property="og:description"
          content="Startup Briefs is a platform which reduces the length of news while retaining the content, hence saving time of reader">
    <meta property="og:image" content="https://s3.amazonaws.com/vaetas/images/startup_briefs_logo.png">
    <meta property="og:rich_attachment" content="true">

    {{--Google--}}
    <meta name="author" content="Invidz, LLC"/>
    <meta name="copyright" content="Invidz, LLC"/>
    <meta name="application-name" content="VaetasNews"/>
@endsection

@section('content')
    <div class="container">
        @if(isset($edited))
            <div id="alert" class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                <strong>Success!</strong> Your Story was edited successfully!
            </div>
        @endif
        @if(isset($deleted))
            <div id="alert" class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                <strong>Success!</strong> Your Story was deleted successfully!
            </div>
        @endif
        @if(isset($forEdit))
            <div class="row ck-center" style="width: 900px;">
                <form action="{{url('/fetchLink')}}" method="post">
                    <div class="form-inline">
                        {{csrf_field()}}
                        <input type="text" style="width: 800px;" id="link" name="link" class="form-control"
                               placeholder="Enter the link of an external news.">
                        <input type="submit" class="btn btn-primary pull-right" value="Submit">
                    </div>
                </form>
            </div>

        @endif
        <div class="row">
            @foreach($stories as $story)
                <div class="ck-card ck-center">
                    <div class="ck-news-image">
                        <img src="{{ $story->thumbnail_url }}" class="ck-thumbnail">
                    </div>
                    @if (!Auth::guest())
                        <a class="pull-right" href="{{ url("/stories/$story->id/edit") }}"><i
                                    class="fa fa-lg fa-pencil"></i></a>
                    @endif
                    <div class="ck-pull-right ck-card-title">
                        <a target="_blank" style="color:#44444d!important"
                           href="{{ $story->article_link }}">
                            {{ $story->title }}
                        </a>
                    </div>
                    <div class="ck-pull-right ck-card-content">
                        {{ $story->description }}
                    </div>

                    <div class="ck-share">
                        <a target="_blank"
                           href="https://www.facebook.com/sharer.php?u={{urlencode(url("/stories/$story->slug"))}}"><i
                                    class="fa fa-lg fa-facebook-official" aria-hidden="true"></i></a>
                        <a target="_blank"
                           href="https://plus.google.com/share?url={{url("/stories/$story->slug")}}"><i
                                    class="fa fa-lg fa-google-plus" aria-hidden="true"></i></a>
                        <a target="_blank"
                           href="https://www.twitter.com/share?text={{$story->title}}&orginal_referer={{url("/stories/$story->slug")}}&url={{url("/stories/$story->slug")}}"><i
                                    class="fa fa-lg fa-twitter" aria-hidden="true"></i></a>
                        <a target="_blank"
                           href="https://www.linkedin.com/shareArticle?mini=true&url={{urlencode(url("/stories/$story->slug"))}}&title={{urlencode($story->title)}}&summary={{urlencode($story->description)}}&source=Startup Briefs"><i
                                    class="fa fa-lg fa-linkedin" aria-hidden="true"></i></a>
                    </div>
                </div>
            @endforeach
        </div>
        <div class="row">
            <div class="ck-pagination">
                {{ $stories->render() }}
            </div>
        </div>
    </div>
    <script>
        jQuery(document).ready(function ($) {
            $('#alert').delay(5000).slideUp('slow');
        });
    </script>
@endsection

resources/views/storyView.blade.php
@extends('layouts.app')
@section('meta')
    {{--Twitter--}}
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="{{$story->title}}">
    <meta name="twitter:description" content="{{$story->description}}">
    <meta name="twitter:image" content="{{("$story->thumbnail_url")}}">

    {{--Facebook--}}
    <meta property="fb:app_id" content="1648507378769295" >
    <meta property="og:url" content="{{url("/stories/$story->slug")}}" >
    <meta property="og:type" content="Startup Briefs">
    <meta property="og:title" content="{{$story->title}}" >
    <meta property="og:description" content="{{$story->description}}" >
    <meta property="og:image" content="{{("$story->thumbnail_url")}}" >
    <meta property="og:image:width" content="100" >
    <meta property="og:image:height" content="100" >
    <meta property="og:rich_attachment" content="true">

    {{--Google--}}
    <meta name="author" content="Invidz, LLC" />
    <meta name="copyright" content="Invidz, LLC" />
    <meta name="application-name" content="VaetasNews" />
@endsection
<title>
    {{$story->title}}
</title>
@section('header')
    <link rel="stylesheet" href={{ url('/css/stories.css') }}>
@endsection
@section('content')
    <div class="container">
        <div class="row">
            <div class="ck-card ck-center">
                <div class="ck-news-image">
                    <img src="{{ $story->thumbnail_url }}" class="ck-thumbnail">
                </div>
                <div class="ck-pull-right ck-card-title">
                    <a target="_blank" style="color:#44444d!important" href="{{ $story->article_link }}">
                        {{ $story->title }}
                        @if (!Auth::guest())
                            <a class="pull-right" href="{{ url("/stories/$story->id/edit") }}"><i class="fa fa-pencil"></i></a>
                        @endif
                    </a>
                </div>
                <div class="ck-pull-right ck-card-content">
                    {{ $story->description }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/success.blade.php
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    <title>Success</title>

    <link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">

    <style>
        html, body {
            height: 100%;
        }

        body {
            margin: 0;
            padding: 0;
            width: 100%;
            color: #B0BEC5;
            display: table;
            font-weight: 100;
            font-family: 'Lato';
        }

        .container {
            text-align: center;
            display: table-cell;
            vertical-align: middle;
        }

        .content {
            text-align: center;
            display: inline-block;
        }

        .title {
            font-size: 72px;
            margin-bottom: 40px;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="content">
        <div class="title">Success.<i class="fa fa-small fa-check"></i></div>
        <div class="title"><a href="{{ url('/') }}"><i class="fa fa-small fa-home"></i></a> | <a href="{{ url('/stories/create') }}">Create Another Story</a></div>
    </div>
</div>
</body>
</html>